// ==============================================================
// SecureBank — Auth Module Zod Validators
// ==============================================================

import { z } from 'zod';
import { emailSchema, passwordSchema, nameSchema, phoneSchema, totpCodeSchema, uuidSchema } from '../../shared/validation';
import { KycDocumentType } from '@prisma/client';

export const registerSchema = z.object({
  body: z.object({
    email: emailSchema,
    password: passwordSchema,
    firstName: nameSchema,
    lastName: nameSchema,
    phone: phoneSchema,
  }),
});

export const loginSchema = z.object({
  body: z.object({
    email: emailSchema,
    password: z.string().min(1, 'Password is required'),
    totpCode: totpCodeSchema.optional(), // Only required if MFA is enabled
  }),
});

export const verifyMfaSchema = z.object({
  body: z.object({
    code: totpCodeSchema,
  }),
});

export const setupMfaSchema = z.object({
  body: z.object({
    code: totpCodeSchema, // The code generated by the user's authenticator app to verify setup
  }),
});

export const uploadKycSchema = z.object({
  body: z.object({
    type: z.nativeEnum(KycDocumentType),
  }),
  // Note: The actual file will be validated by multer (or similar) middleware
});

export const refreshTokenSchema = z.object({
  body: z.object({
    refreshToken: z.string().min(1, 'Refresh token is required'),
  }),
});

export const resetPasswordRequestSchema = z.object({
  body: z.object({
    email: emailSchema,
  }),
});

export const resetPasswordConfirmSchema = z.object({
  body: z.object({
    token: z.string().min(1, 'Reset token is required'),
    newPassword: passwordSchema,
  }),
});
