apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: securebank-prod
resources:
  - ../../base
  - ../../namespaces
  - ../../rbac
  - ../../network-policies
  - ingress.yaml
  - hpa.yaml
namePrefix: prod-
images:
  - name: securebank/api
    newName: ghcr.io/ahlemhidri01/securebank-api
    newTag: "e88bd24"
