apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - networkpolicy.yaml
  - ingress.yaml

namePrefix: prod-

images:
  - name: securebank/api
    newName: myregistry.azurecr.io/securebank/api
    newTag: latest # This will be automatically patched by the CI pipeline

patchesStrategicMerge:
  - hpa.yaml # Horizontal Pod Autoscaler for prod
